- src/components/layout/Layout.jsx
- src/components/layout/footer/Footer.jsx
🔀 merge: from feature/footer to dev
> ✨ feat: footer 생성

- src/components/layout/Layout.jsx
- src/components/layout/footer/Footer.jsx
- src/pages/community/Community.jsx
- src/pages/community/CommunityForMe.jsx
- src/pages/community/FeedList.jsx
🔀 merge: from feature/header to dev
> ✨ feat: Community Page 생성 및 초기작업

- src/assets/icon-close.svg
- src/assets/icon-menu.svg
- src/components/layout/header/Header.jsx
- src/components/layout/header/Header.style.jsx
- src/hooks/useWindowWide.mjs
- src/index.css
🔀 merge: from feature/header to dev
> ✅ update: header 기능 수정

- src/pages/meditation/Meditation.jsx
> ✨ feat: 명상 페이지 생성

- src/pages/home/Home.jsx
🔀 merge: from feature/home to dev
> ✅ update: 메인 페이지 수정

- src/components/button/Button.jsx
- src/components/button/Button.style.jsx
- src/index.css
- src/pages/meditation/Meditation.jsx
> 💄 style: 명상 페이지 스타일링 / ✅ add: Button 컴포넌트 생성

- src/components/layout/layout/Layout.style.jsx
- src/hooks/useClickOutside.mjs
- src/index.css
- src/pages/meditation/Meditation.jsx
> ✨ feat: 명상 시간 설정 기능 추가

- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/ReplyCreate.jsx
- src/pages/community/feed/ReplyList.jsx
- src/pages/community/user/UserInfo.jsx
- src/routes.jsx
> 🚧 cont: 댓글추가 및 댓글창 수정

- src/components/button/Button.jsx
- src/components/button/Button.style.jsx
- src/components/layout/header/Header.jsx
- src/components/result/Result.jsx
- src/components/result/Result.style.jsx
- src/components/timer/Timer.jsx
- src/pages/meditation/Meditation.jsx
- src/pages/meditation/Meditation.style.jsx
- src/pages/meditation/MeditationMain.jsx
- src/pages/meditation/MeditationProgress.jsx
- src/pages/meditation/MeditationRecord.jsx
- src/routes.jsx
- src/zustand/timer.mjs
> ✨ feat: 타이머 기능 생성 / ✨ feat: 명상 기록 페이지 생성

- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/FeedDropdown.jsx
- src/pages/community/feed/ReplyCreate.jsx
- src/pages/community/feed/ReplyList.jsx
> ✨ feat:  FeedDropDown 버튼에 useClickOutSide 적용

- src/components/layout/header/Header.jsx
- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedCreate.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/FeedDropdown.jsx
- src/pages/community/feed/FeedEdit.jsx
- src/pages/community/feed/FeedNew.jsx
- src/pages/community/feed/ReplyCreate.jsx
- src/pages/community/mypage/MyPage.jsx
- src/routes.jsx
> ✨feat: Mypage 파일추가, routes 설정, create버튼 스타일 변경

- package-lock.json
- package.json
- src/components/calendar/Calendar.jsx
- src/components/layout/footer/Footer.jsx
- src/pages/community/ErrorStyled.jsx
- src/pages/community/feed/FeedCreate.jsx
- src/pages/community/feed/FeedNew.jsx
- src/pages/community/feed/ReplyCreate.jsx
- src/pages/community/mypage/EditProfile.jsx
- src/pages/community/mypage/MyInfo.jsx
- src/pages/community/mypage/MyInfoCheck.jsx
- src/pages/community/mypage/MyInfoEdit.jsx
- src/pages/community/mypage/MyPage.jsx
- src/pages/community/mypage/MyRecord.jsx
- src/routes.jsx
> ✨ feat: MyPage, MyInfo, MyInfoCheck 페이지 작업 / ✨ feat: MyInfo,Infocheck,Infoedit,Mypage, 페이지 추가

- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/ReplyCreate.jsx
> 🚧 cont: 기능수정중

- api/API-Client/관리자 - 테마 등록/테마 등록.bru
- api/API-Client/관리자 - 테마 등록/테마 삭제.bru
- api/API-Client/회원 - 이미지/이미지 링크.bru
- src/components/themeset/ThemeMenu.jsx
- src/pages/meditation/MeditationMain.jsx
- src/pages/meditation/MeditationProgress.jsx
- src/pages/meditation/MeditationRecord.jsx
- src/pages/purchase/Purchase.jsx
> ♻️ refactor: zustand 호출 리팩토링 / 🗃️ data: bruno 업데이트

- src/components/button/Button.style.jsx
- src/components/layout/header/Header.jsx
- src/components/layout/header/Header.style.jsx
- src/hooks/useCustomAxios.mjs
- src/pages/meditation/MeditationRecord.jsx
- src/pages/users/Login.jsx
- src/routes.jsx
🔀 merge: from feature/login to dev
> ✨ feat: 로그인 기능 구현

- api/API-Client/회원 - 커뮤니티/게시물 조회.bru
- src/pages/community/feed/FeedList.jsx
> 🚧 cont: FeedList 수정중

- src/zustand/themeSelection.mjs
- src/zustand/timeSelection.mjs
- src/zustand/timer.mjs
> ✅ update: 시간, 테마 상태관리 업데이트

- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/FeedList.jsx
> ♻️refactor: Feed 페이지 코드 리팩토링 중 / ✅ passtest: 서버통신 성공

- src/components/layout/header/Header.style.jsx
> 💄 style: header 아이콘 경로 변경

- src/components/layout/header/Header.jsx
- src/components/layout/header/Header.style.jsx
- src/components/themeset/ThemeMenu.jsx
- src/components/themeset/ThemeSet.style.jsx
- src/pages/ErrorPage.jsx
- src/pages/purchase/Purchase.jsx
- src/pages/purchase/Purchase.style.jsx
- src/routes.jsx
> ✨ feat: 에러 페이지 추가 / 💄 style: 가상 요소 이미지 링크 수정, modal 너비 수정

- src/components/layout/header/Header.style.jsx
- src/pages/home/Home.jsx
- src/pages/home/HomeCarousel.jsx
🔀 merge: from feature/home to dev
> 💄 style: Header 스타일 수정 / 🚧 cont: Home 화면 작업 진행중

- api/API-Client/파일 등록/이미지 업로드.bru
🔀 from feature/meditation to dev
> 🗃️ data: bruno 수정

- src/components/layout/header/Header.style.jsx
- src/components/styles/GlobalStyle.jsx
🔀 merge: from feature/home to dev
> 💄 style: Header 모바일 메뉴 확장 시 background 수정

- src/pages/purchase/Purchase.jsx
- src/pages/purchase/Purchase.style.jsx
> 💄 style: Checkbox icon 대신 CSS로 수정

- src/components/layout/header/Header.style.jsx
🔀 merge: from feature/home to dev
> 💄 style: Header 스타일 padding 수정

- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/FeedDropdown.jsx
- src/pages/community/feed/FeedList.jsx
- src/pages/community/feed/ReplyCreate.jsx
- src/pages/community/feed/ReplyList.jsx
- src/pages/community/feed/Search.jsx
> 🚧 cont: FeedList 화면 기능수정중

- src/pages/community/mypage/MyInfo.jsx
- src/pages/community/mypage/MyInfoCheck.jsx
- src/pages/community/mypage/MyPage.jsx
- src/routes.jsx
> ♻️ refactor: routes path 변경

- src/pages/users/SignUp.jsx
> ✅ update: 프로필 이미지 등록 수정

- index.html
- src/App.jsx
- src/hooks/useCustomAxios.mjs
- src/pages/meditation/MeditationRecord.jsx
- src/pages/meditation/themeset/ThemeMenu.jsx
- src/pages/meditation/timer/Timer.jsx
- src/pages/purchase/Purchase.jsx
- src/pages/users/SignUp.jsx
- src/routes.jsx
- src/zustand/modal.mjs
> 🚧 cont: 모달창 수정 중 / ✅ update: 모달 App에서 관리 / 🐛 fix: router 경로 수정 / 🐛 fix: 테마를 이미 구매한 경우 핸들링 / ✅ update: 모달 App에서 관리 완료

- package.json
- src/App.jsx
- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedCreate.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/FeedDropdown.jsx
- src/pages/community/feed/FeedList.jsx
- src/pages/community/feed/FeedNew.jsx
- src/pages/community/user/UserInfo.jsx
FeedCreate 클릭 시 FeedNew 로 넘어가서 FeedList 에 글 추가
게시글 수정, 삭제 기능 추가
FeedDetail 화면에 클릭 한 글 렌더링
> ♻️ refactor: Feed 에 글목록 렌더링

- api/API-Client/파일 등록/이미지 업로드.bru
- api/API-Client/회원 - 로그인/로그인.bru
- api/API-Client/회원 - 로그인/회원가입.bru
- api/API-Client/회원 - 커뮤니티/게시물 조회.bru
- api/API-Client/회원 - 커뮤니티/댓글 등록.bru
- api/API-Client/회원 - 커뮤니티/댓글 조회.bru
- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedList.jsx
- src/pages/community/feed/FeedNew.jsx
- src/pages/community/feed/ReplyList.jsx
- src/pages/community/user/UserInfo.jsx
> ✨feat: Feed에 각 userprofile 표시

- src/pages/purchase/Purchase.jsx
> 🐛 fix: 결제 시 미리듣기 중지 수정

- package-lock.json
- package.json
- src/components/input/Input.jsx
- src/components/input/Input.style.jsx
- src/pages/admin/UploadTheme.jsx
- src/pages/meditation/Meditation.style.jsx
- src/pages/meditation/MeditationProgress.jsx
- src/pages/meditation/MeditationRecord.jsx
- src/pages/purchase/Purchase.jsx
- src/pages/purchase/Purchase.style.jsx
> ✅ update: input 컴포넌트로 변경 / ✅ update: SoundCloud 이용 / 🐛 fix: 미리듣기 시간 수정 / 🚧 cont: 테마 등록 페이지 작업 중

- api/API-Client/회원 - 로그인/회원 정보 조회.bru
- package-lock.json
- package.json
- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/FeedDropdown.jsx
- src/pages/community/feed/FeedEdit.jsx
- src/pages/community/feed/FeedList.jsx
- src/pages/community/feed/ReplyCreate.jsx
- src/pages/community/feed/ReplyList.jsx
- src/pages/community/user/UserInfo.jsx
> ✨ feat: Login유저 댓글

- src/pages/admin/UploadTheme.jsx
> 🚧 cont: react-color 작업 중

- src/components/button/Button.style.jsx
- src/components/input/Input.jsx
- src/components/layout/header/Header.style.jsx
- src/pages/admin/UploadTheme.jsx
- src/pages/admin/UploadTheme.style.jsx
- src/pages/meditation/MeditationRecord.jsx
- src/pages/purchase/Purchase.style.jsx
> 🚧 cont: 테마 등록 페이지 작업 중

- api/dbinit/team/data.js
- src/components/input/Input.style.jsx
- src/components/layout/header/Header.style.jsx
- src/pages/admin/UploadTheme.jsx
- src/pages/admin/UploadTheme.style.jsx
> ✅ update: 테마 등록 페이지 완료

- src/components/layout/header/Header.jsx
- src/components/modal/ModalWindow.jsx
- src/components/modal/ModalWindow.style.jsx
- src/pages/home/Home.jsx
> 🚧 cont: 회원가입 작업 진행중

- src/pages/admin/UploadTheme.jsx
- src/pages/meditation/MeditationProgress.jsx
- src/pages/meditation/MeditationRecord.jsx
- src/pages/meditation/themeset/ThemeMenu.jsx
- src/pages/meditation/themeset/themeitem/ThemeItem.jsx
- src/pages/meditation/themeset/themeitem/ThemeItem.style.jsx
- src/pages/purchase/Purchase.jsx
> ✨ feat: 테마 삭제 기능 생성

- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/ReplyList.jsx
🔀 merge: from feature/feedmain to dev
> 🚧 cont: Feed 오류 작업 중

- src/pages/community/feed/FeedEdit.jsx
🔀 merge: from feature/edit to dev
> 🚧 cont: FeedEdit PATCH 시도

- src/components/modal/ModalWindow.jsx
- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/Feed.style.jsx
- src/pages/community/feed/FeedDetail.jsx
- src/pages/community/feed/FeedNew.jsx
- src/pages/community/feed/PostDetail.jsx
- src/pages/community/feed/ReplyItem.jsx
- src/pages/community/feed/ReplyList.jsx
- src/pages/community/feed/dropdown/FeedDropdown.jsx
- src/pages/meditation/MeditationRecord.jsx
🔀 merge: from feature/feeddetail to dev
> 🚧 cont: FeedDetail 작업 중

- src/pages/mypage/MyPage.jsx
> 🚧 cont: Mypage username 렌더링

- src/pages/mypage/MyPage.jsx
> ✨ feat: MyPage 나의기록 recordList 렌더링 작업

- src/pages/home/Home.jsx
- src/pages/home/HomeCarousel.jsx
> 🐛 fix: Home import 경로 수정

- src/pages/users/SignUpOneStep.jsx
- src/pages/users/SignUpTwoStep.jsx
- src/zustand/form.mjs
> 🚧 cont: 회원가입 화면 작업중

- api/API-Client/회원 - 로그인/Access 토큰 확인.bru
- src/pages/mypage/EditProfile.jsx
- src/pages/mypage/MyInfo.jsx
- src/pages/mypage/MyInfoCheck.jsx
- src/pages/mypage/MyPage.jsx
,MyInfo 데이터 렌더링 프로필 수정 클릭시 MyInfoCheck 페이지로 이동
MyInfoCheck 비밀번호 인증
> ✨feat: Mypage archive 기록, 내정보보기 클릭시 MyInfo 페이지로 이동

- src/pages/meditation/MeditationProgress.jsx
- src/pages/meditation/MeditationRecord.jsx
> ✅ update: 기록 저장 시 테마 배경 전송

- api/API-Client/회원 - 커뮤니티/북마크 한 글 조회.bru
- api/dbinit/team/data.js
- src/pages/community/feed/Feed.style.jsx
- src/pages/community/feed/FeedList.jsx
- src/pages/community/feed/editor/FeedEditorEdit.jsx
- src/pages/community/feed/reply/ReplyList.jsx
- src/pages/mypage/myactivity/BookmarkedPosts.jsx
- src/pages/mypage/myactivity/MyActivity.jsx
- src/pages/mypage/myactivity/MyPosts.jsx
- src/routes.jsx
🔀 merge: from feature/activity to dev
> ✅ update: 나의 활동 페이지 완료

- src/pages/meditation/MeditationRecord.jsx
- src/pages/mypage/EditProfile.jsx
- src/pages/mypage/MyPage.jsx
> 🚧 cont: EditProfile 회원정보 수정 ㅇ수정중

- src/pages/users/SignUpOneStep.jsx
- src/pages/users/SignUpTwoStep.jsx
> ✅ update: 회원가입 완료

- src/pages/community/feed/FeedList.jsx
- src/pages/community/feed/PostDetail.jsx
- src/pages/community/feed/editor/FeedEditorEdit.jsx
- src/pages/community/feed/editor/FeedEditorNew.jsx
> 🐛 fix: Feed 이미지 업로드 형식, alt 수정

- src/pages/users/SignUpTwoStep.jsx
🔀 merge: from feature/social to dev
> ✅ add: 회원가입 시 로그인타입 추가, 회원가입 시 기본 이미지 경로 수정 / ✅ add: 소셜로그인을 위한 auth 폴더 추가

- src/pages/auth/kakao.jsx
- src/pages/users/SignUpOneStep.jsx
- src/pages/users/SignUpTwoStep.jsx
🔀 merge: from feature/social to dev
> ✨ feat: 회원가입 시 이메일 중복 체크 추가 / 🚧 cont: 카카오 소셜 로그인 작업중  @danggin

- api/API-Client/회원 - 커뮤니티/사용자가 작성한 게시글 목록.bru
- src/pages/mypage/EditProfile.jsx
- src/pages/mypage/MyInfo.jsx
- src/pages/mypage/MyInfoCheck.jsx
- src/pages/mypage/MyPage.jsx
> ✨ feat: Myinfo 정보 렌더링, MyPage 정보 렌더링,

- api/dbinit/team/data.js
- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/Feed.style.jsx
- src/pages/community/feed/editor/FeedEditorEdit.jsx
- src/pages/community/feed/editor/FeedEditorNew.jsx
- src/pages/community/feed/reply/ReplyList.jsx
- src/pages/mypage/myactivity/MyPosts.jsx
🔀 merge: from feature/myactivity to dev
> 🚧 cont: 내가 쓴 글 무한스크롤 작업 중

- src/pages/mypage/EditProfile.jsx
- src/pages/mypage/MyPage.jsx
> ✨feat:MyPage 데이터수정, EditProfile 데이터수정 및 비밀번호 변경 토글버튼생성

- api/API-Client/회원 - 로그인/이메일 중복체크.bru
- api/API-Client/회원 - 로그인/카카오 로그인.bru
- src/components/socialLogin/SocialKakao.jsx
- src/pages/auth/kakao.jsx
- src/routes.jsx
🔀 merge: from feature/kakao to dev
> 🚧 cont: 카카오 로그인 작업 중

- api/API-Client/회원 - 로그인/카카오 로그인.bru
- src/pages/auth/Kakao.jsx
- src/pages/community/feed/Feed.jsx
- src/pages/community/feed/FeedEdit.jsx
- src/pages/community/feed/FeedList.jsx
- src/pages/community/feed/FeedNew.jsx
- src/pages/community/feed/PostDetail.jsx
- src/pages/community/feed/reply/ReplyItem.jsx
- src/pages/community/feed/reply/ReplyList.jsx
- src/pages/community/feed/reply/ReplyNew.jsx
🔀 merge: from feature/kakao to dev
> ✅ update: 카카오 로그인 및 프로필 불러오기 완료

- src/pages/users/SignUp.style.jsx
- src/pages/users/SignUpOneStep.jsx
- src/pages/users/SignUpTwoStep.jsx
> 💄 로그인, 회원가입 화면 CSS 작업 완료

- src/pages/mypage/EditProfile.jsx
- src/pages/mypage/MyInfo.jsx
- src/pages/mypage/MyInfoCheck.jsx
- src/pages/mypage/MyPage.jsx
> 🚧 cont: EditProfile 대공사중

- api/API-Client/environments/prod.bru
- src/pages/error/ErrorPage.jsx
- src/pages/mypage/EditProfile.jsx
- src/pages/mypage/MyInfo.jsx
- src/pages/mypage/MyInfoCheck.jsx
- src/pages/mypage/MyPage.jsx
- src/pages/users/Login.jsx
🔀 merge: from feature/editprofile to dev
> ✅ update: 회원정보 수정 완료

- src/components/loading/Loading.jsx
- src/pages/users/Login.jsx
- src/pages/users/SignUpOneStep.jsx
- src/pages/users/SignUpTwoStep.jsx
> ✅ add: 회원가입 시 비밀번호 확인 검증 로직 추가, 회원가입 완료 alert을 모달창으로 수정 / ✅ add: 회원가입 첫번째 화면에 로딩 화면 추가 / 💄 style: 로딩 화면 CSS 수정

- package-lock.json
- package.json
- src/components/calendar/Calendar.jsx
- src/components/calendar/Calendar.style.jsx
- src/pages/mypage/EditProfile.jsx
- src/pages/mypage/MyPage.jsx
- src/pages/mypage/MyRecord.jsx
💄styles: EditProfile 스타일 수정, styled component 분리시 오류 (<Toggle>)
>  ✨feat: Calendar 생성, MyRecord 페이지 ,

- README.md
- src/components/animation/Animation.jsx
- src/components/layout/header/Header.jsx
- src/components/layout/header/Header.style.jsx
- src/components/layout/layout/Layout.style.jsx
- src/pages/home/Home.jsx
- src/pages/home/Home.style.jsx
- src/pages/users/SignUp.style.jsx
- src/pages/users/SignUpOneStep.jsx
- src/pages/users/SignUpTwoStep.jsx
🔀 merge: from feature/header to dev
> 💄 style: Header, Home CSS 수정

- src/pages/community/feed/create/FeedCreate.style.jsx
🔀 merge: from feature/kiho to dev
> ♻️ refactor: FeedCreate 버튼 위치 반응형에 맞게 중앙정렬

- src/components/calendar/Calendar.jsx
- src/hooks/useDate.js
events가 들어 있는 쎌 클릭시 modal창 열리지 않도록 수정
> ♻️ refactor: calendar 변경버튼 클릭시 해당 월에 맞게 레이아웃변경

- src/components/calendar/Calendar.jsx
- src/components/calendar/Calendar.style.jsx
화면 줄어들면 명상 한줄 기록, modal창 내 font-size 조절
> ♻️ refactor: Calendar.jsx next 버튼 svg로 변경
